/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import HomeLanding.HomeLanding;
import javax.swing.JFrame;

/**
 *
 * @author sunilrudrakumar
 */
public class AdminLandingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public AdminLandingJFrame() {
        initComponents();
     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnVehicleAdmin3 = new javax.swing.JButton();
        btnGadgetAdmin3 = new javax.swing.JButton();
        btnVehicleServicesAdmin3 = new javax.swing.JButton();
        btnGadgetServicesAdmin3 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jSplitPane2.setBackground(new java.awt.Color(51, 51, 0));

        jPanel3.setBackground(new java.awt.Color(255, 185, 12));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Admins");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, -1, -1));

        btnVehicleAdmin3.setBackground(new java.awt.Color(51, 51, 0));
        btnVehicleAdmin3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnVehicleAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicleAdmin3.setText("Vehicle Admin");
        btnVehicleAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnVehicleAdmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 197, 166, -1));

        btnGadgetAdmin3.setBackground(new java.awt.Color(51, 51, 0));
        btnGadgetAdmin3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGadgetAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnGadgetAdmin3.setText("Gadget Admin");
        btnGadgetAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadgetAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnGadgetAdmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 250, 166, -1));

        btnVehicleServicesAdmin3.setBackground(new java.awt.Color(51, 51, 0));
        btnVehicleServicesAdmin3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnVehicleServicesAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicleServicesAdmin3.setText("Vehicle Services Admin");
        btnVehicleServicesAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleServicesAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnVehicleServicesAdmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 316, -1, -1));

        btnGadgetServicesAdmin3.setBackground(new java.awt.Color(51, 51, 51));
        btnGadgetServicesAdmin3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGadgetServicesAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnGadgetServicesAdmin3.setText("Gadget Services Admin");
        btnGadgetServicesAdmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGadgetServicesAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnGadgetServicesAdmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 378, 166, -1));

        Logout.setBackground(new java.awt.Color(51, 51, 0));
        Logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnGadgetAdminActionPerformed(evt);
            }
        });
        jPanel3.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 490, 99, 33));

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGadgetServicesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadgetServicesAdminActionPerformed
        GadgetServicesAdminPanel view = new GadgetServicesAdminPanel();
        jSplitPane2.setRightComponent(view);// TODO add your handling code here:
    }//GEN-LAST:event_btnGadgetServicesAdminActionPerformed

    private void btnVehicleServicesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleServicesAdminActionPerformed
        VehicleServicesAdminPanel view = new VehicleServicesAdminPanel();
        jSplitPane2.setRightComponent(view);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehicleServicesAdminActionPerformed

    private void btnGadgetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGadgetAdminActionPerformed
        GadgetAdminPanel view = new GadgetAdminPanel();
        jSplitPane2.setRightComponent(view);// TODO add your handling code here:
    }//GEN-LAST:event_btnGadgetAdminActionPerformed

    private void btnVehicleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleAdminActionPerformed
        VehicleAdminPanel view = new VehicleAdminPanel();
        jSplitPane2.setRightComponent(view);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehicleAdminActionPerformed

    private void LogoutbtnGadgetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnGadgetAdminActionPerformed
        // TODO add your handling code here:
        HomeLanding hm = new HomeLanding();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutbtnGadgetAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLandingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLandingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnGadgetAdmin3;
    private javax.swing.JButton btnGadgetServicesAdmin3;
    private javax.swing.JButton btnVehicleAdmin3;
    private javax.swing.JButton btnVehicleServicesAdmin3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
