/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CarRental;


import HomeLanding.HomeLanding;
import HomeLanding.VehicleAdminLandingPage;
import Rental.Notification.Email;
import MySQLConnection.MySQLConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author tejas
 */
public class RentCarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageCarJFrame
     */
    MySQLConnection c = new MySQLConnection();
    Email e = new Email();
    public RentCarJFrame() {
        initComponents();
        DisplayCarOnRent();
        DisplayCarRentalRequest();
        TxtRegNo.setEditable(false);
        TxtCustomerID.setEditable(false);
        TxtRentDate.setEditable(false);
        TxtReturnDate.setEditable(false);
        TxtPrice.setEditable(false);
//     ss   TxtProductId.setEditable(false);
        TxtEmail.setVisible(false);
        jLabel9.setVisible(false);
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RentCarPanel = new javax.swing.JPanel();
        LblRentCarHeading = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        BtnReturnCar = new javax.swing.JButton();
        BtnManageCar = new javax.swing.JButton();
        BtnReturnCar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblCarOnRent = new javax.swing.JTable();
        LblCarsOnRent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblCarRentalRequest = new javax.swing.JTable();
        TxtCustomerID = new javax.swing.JTextField();
        TxtRentDate = new javax.swing.JTextField();
        TxtRegNo = new javax.swing.JTextField();
        BtnApprove = new javax.swing.JButton();
        BtnDeny = new javax.swing.JButton();
        TxtReturnDate = new javax.swing.JTextField();
        TxtPrice = new javax.swing.JTextField();
        TxtRentID = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        LblCarsOnRent1 = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        lblCustomerId1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RentCarPanel.setBackground(new java.awt.Color(51, 51, 0));
        RentCarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblRentCarHeading.setBackground(new java.awt.Color(255, 185, 12));
        LblRentCarHeading.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LblRentCarHeading.setForeground(new java.awt.Color(255, 185, 12));
        LblRentCarHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblRentCarHeading.setText("Rent Cars");
        LblRentCarHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RentCarPanel.add(LblRentCarHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 102, 185, 53));

        ButtonsPanel.setBackground(new java.awt.Color(255, 185, 12));
        ButtonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturnCar.setBackground(new java.awt.Color(51, 51, 0));
        BtnReturnCar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnReturnCar.setForeground(new java.awt.Color(255, 255, 255));
        BtnReturnCar.setText("Manage Returns");
        BtnReturnCar.setBorder(null);
        BtnReturnCar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnReturnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnCarActionPerformed(evt);
            }
        });
        ButtonsPanel.add(BtnReturnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 343, -1, 29));

        BtnManageCar.setBackground(new java.awt.Color(51, 51, 0));
        BtnManageCar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnManageCar.setForeground(new java.awt.Color(255, 255, 255));
        BtnManageCar.setText("Manage Cars");
        BtnManageCar.setBorder(null);
        BtnManageCar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageCarActionPerformed(evt);
            }
        });
        ButtonsPanel.add(BtnManageCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 270, 125, 29));

        BtnReturnCar2.setBackground(new java.awt.Color(51, 51, 0));
        BtnReturnCar2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnReturnCar2.setForeground(new java.awt.Color(255, 255, 255));
        BtnReturnCar2.setText("Back");
        BtnReturnCar2.setBorder(null);
        BtnReturnCar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnReturnCar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnCar2ActionPerformed(evt);
            }
        });
        ButtonsPanel.add(BtnReturnCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 552, 115, 29));

        RentCarPanel.add(ButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 1200));

        TblCarOnRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rent ID", "Customer ID", "Rent Fee"
            }
        ));
        TblCarOnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCarOnRentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblCarOnRent);

        RentCarPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 222, 430, 129));

        LblCarsOnRent.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LblCarsOnRent.setForeground(new java.awt.Color(255, 185, 12));
        LblCarsOnRent.setText("Rental Request");
        RentCarPanel.add(LblCarsOnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 386, 125, -1));

        TblCarRentalRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Reg No", "Rent Date", "Return Date", "Fee"
            }
        ));
        TblCarRentalRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCarRentalRequestMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblCarRentalRequest);

        RentCarPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 430, 139));

        TxtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCustomerIDActionPerformed(evt);
            }
        });
        RentCarPanel.add(TxtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 164, 144, 34));
        RentCarPanel.add(TxtRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 347, 144, 37));
        RentCarPanel.add(TxtRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 224, 144, 40));

        BtnApprove.setBackground(new java.awt.Color(255, 185, 12));
        BtnApprove.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnApprove.setForeground(new java.awt.Color(255, 255, 255));
        BtnApprove.setText("Approve");
        BtnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApproveActionPerformed(evt);
            }
        });
        RentCarPanel.add(BtnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, -1, -1));

        BtnDeny.setBackground(new java.awt.Color(255, 185, 12));
        BtnDeny.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnDeny.setForeground(new java.awt.Color(255, 255, 255));
        BtnDeny.setText("Deny");
        BtnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDenyActionPerformed(evt);
            }
        });
        RentCarPanel.add(BtnDeny, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 94, -1));
        RentCarPanel.add(TxtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 397, 144, 37));
        RentCarPanel.add(TxtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 448, 144, 40));
        RentCarPanel.add(TxtRentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 282, 144, 39));
        RentCarPanel.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 505, 144, 33));

        LblCarsOnRent1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LblCarsOnRent1.setForeground(new java.awt.Color(255, 185, 12));
        LblCarsOnRent1.setText("Cars On Rent");
        RentCarPanel.add(LblCarsOnRent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 183, 125, -1));

        lblCustomerId.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(255, 185, 12));
        lblCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerId.setText("Customer ID :");
        RentCarPanel.add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 164, 116, 40));

        lblCustomerId1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCustomerId1.setForeground(new java.awt.Color(255, 185, 12));
        lblCustomerId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerId1.setText("Reg No :");
        RentCarPanel.add(lblCustomerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 222, 116, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 185, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rent ID :");
        RentCarPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 282, 94, 37));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 185, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Rent Date :");
        RentCarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 347, 94, 37));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 185, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Return Date :");
        RentCarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 396, -1, 37));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 185, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fee :");
        RentCarPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 446, 70, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 185, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Email :");
        RentCarPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 500, 94, 41));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 185, 12));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Great Value Enterprises");
        RentCarPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 6, -1, -1));

        getContentPane().add(RentCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReturnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnCarActionPerformed
        // TODO add your handling code here:
        ReturnCarJFrame rc = new ReturnCarJFrame();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnReturnCarActionPerformed

    private void BtnManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageCarActionPerformed
        // TODO add your handling code here:
        ManageCarJFrame mc = new ManageCarJFrame();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnManageCarActionPerformed

    private void TxtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCustomerIDActionPerformed

    private void BtnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApproveActionPerformed
        // TODO add your handling code here:
        
        
        try{
            int flag = 0;
                
                //*************************************** Validation of Empty Name Field ***************************************//
                 if(TxtRentID.getText().isEmpty()){
                    JOptionPane optionPane = new JOptionPane("Rent ID cannot be empty", JOptionPane.ERROR_MESSAGE);
                    JDialog dialog = optionPane.createDialog("Error Message");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                    flag = 1;
                }
                String cellPhoneNumber3 = TxtRentID.getText();
                Pattern pattern3 = Pattern.compile("^[0-9]{3}$");
                Matcher matcher3 = pattern3.matcher(cellPhoneNumber3);
                if(!matcher3.matches())
                {
                    JOptionPane.showMessageDialog(this,"Enter a Valid Rent ID!");
                    flag = 1;
                    TxtRentID.setText("");
                    
                    
                }
        if(flag == 0){
            String sql="UPDATE car SET customerid = '"+TxtCustomerID.getText()+"', rentid = '"+TxtRentID.getText()+"',status = 'Booked',rentdate = '"+TxtRentDate.getText()+"' ,"
                    + "returndate = '"+TxtReturnDate.getText()+"',price = '"+TxtPrice.getText()+"' WHERE productid = '"+TxtRegNo.getText()+"' ";
            c.updateDatabase(sql);
            JOptionPane.showMessageDialog(this,"Request Aprooved");  
            String sql1 ="UPDATE customers SET caraproove = 'Booked', carrentid = '"+ TxtRentID.getText()+"'  WHERE customerid = '"+TxtCustomerID.getText()+"' ";
            c.updateDatabase(sql1);          

            String sql2 = "SELECT email From customers WHERE customerid = '"+TxtCustomerID.getText()+"'";
            
            ResultSet rs = c.selectDatabase(sql2);
            if(rs.next()){
            String email;
            
            email = rs.getString(1);
//            System.out.println(rs.getString(email));
            TxtEmail.setText(email);
            }
//                       String s =c.selectDatabase(sql2).getString(1);
                       
            String msg = "Your Rental Request has been Aprroved";
            e.sendMail(msg,"Car" ,TxtCustomerID.getText(), TxtRegNo.getText(), TxtRentID.getText(), TxtPrice.getText(),TxtRentDate.getText(), TxtReturnDate.getText(), TxtEmail.getText());
            DisplayCarOnRent();
            DisplayCarRentalRequest();
            Reset();

        }
        }
        catch(Exception e)
        {
        e.printStackTrace();
    }
    }//GEN-LAST:event_BtnApproveActionPerformed

    private void TblCarOnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCarOnRentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblCarOnRentMouseClicked

    private void TblCarRentalRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCarRentalRequestMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TblCarRentalRequest.getModel();
        int MyIndex = TblCarRentalRequest.getSelectedRow();
        TxtCustomerID.setText(model.getValueAt(MyIndex,0).toString());
        TxtRentDate.setText(model.getValueAt(MyIndex,2).toString());
        TxtReturnDate.setText(model.getValueAt(MyIndex,3).toString());
        TxtRegNo.setText((model.getValueAt(MyIndex, 1).toString()));
        TxtPrice.setText((model.getValueAt(MyIndex, 4).toString()));
    }//GEN-LAST:event_TblCarRentalRequestMouseClicked

    private void BtnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDenyActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String sql1 ="UPDATE customers SET caraproove = NULL  WHERE customerid = '"+TxtCustomerID.getText()+"' ";
            c.updateDatabase(sql1);
            JOptionPane.showMessageDialog(this,"Request Denied");
            String msg = "Your Rental request has been Denied";
//            e.sendMail(msg,"Car" ,TxtCustomerID.getText(), TxtRegNo.getText(), TxtRentID.getText(), TxtPrice.getText(),TxtRentDate.getText(), TxtReturnDate.getText(), TxtEmail.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(RentCarJFrame.class.getName()).log(Level.SEVERE, null, ex);
            
        }
            DisplayCarOnRent();
            DisplayCarRentalRequest();
            Reset();
    }//GEN-LAST:event_BtnDenyActionPerformed

    private void BtnReturnCar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnCar2ActionPerformed
        // TODO add your handling code here:
        VehicleAdminLandingPage hl = new VehicleAdminLandingPage();
        hl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnReturnCar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApprove;
    private javax.swing.JButton BtnDeny;
    private javax.swing.JButton BtnManageCar;
    private javax.swing.JButton BtnReturnCar;
    private javax.swing.JButton BtnReturnCar2;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel LblCarsOnRent;
    private javax.swing.JLabel LblCarsOnRent1;
    private javax.swing.JLabel LblRentCarHeading;
    private javax.swing.JPanel RentCarPanel;
    private javax.swing.JTable TblCarOnRent;
    private javax.swing.JTable TblCarRentalRequest;
    private javax.swing.JTextField TxtCustomerID;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtRegNo;
    private javax.swing.JTextField TxtRentDate;
    private javax.swing.JTextField TxtRentID;
    private javax.swing.JTextField TxtReturnDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerId1;
    // End of variables declaration//GEN-END:variables



    private void DisplayCarOnRent() {
        String reg,brand,carmodel,status,price;
        try{
            
            String sql = "select * from car where (status = 'Booked' and rentid IS NOT NULL )";
            ResultSet rs = c.selectDatabase(sql);
            DefaultTableModel model =(DefaultTableModel) TblCarOnRent.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) 
            {
            model.removeRow(i);
            }


            while (rs.next()) 
            {
                reg = rs.getString(2);
                brand = rs.getString(9);
                carmodel = rs.getString(6);
                String[] row = {reg,brand,carmodel};
                model.addRow(row);
                               
             }
        
        } catch (SQLException e)
        {
            e.printStackTrace();
            
            
        }
        
    }

    private void DisplayCarRentalRequest() {
        String reg,brand,status,price,carmodel;
        try{
            String sql = "SELECT * FROM customers where caraproove = 'Requested' ";
            ResultSet rs = c.selectDatabase(sql);
            DefaultTableModel model =(DefaultTableModel)TblCarRentalRequest.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) 
            {
            model.removeRow(i);
            }


            while (rs.next()) {
                reg = rs.getString(1);
                brand = rs.getString(36);
                
                status = rs.getString(43);
                price = rs.getString(47);
                carmodel = rs.getString(39);
                String[] row = {reg,brand,status,price,carmodel};
                model.addRow(row);
                               
            }
        
        } catch (SQLException e)
        {
            e.printStackTrace();
            
            
        }
    }

    private void Reset() {
        TxtCustomerID.setText("");
        TxtEmail.setText("");
        TxtPrice.setText("");
        TxtRegNo.setText("");
        TxtRentDate.setText("");
        TxtRentID.setText("");
        TxtReturnDate.setText("");
    }
}
