/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.BikeRental;

import MySQLConnection.MySQLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author tejas
 */
public class ReturnBikeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBikeJFrame
     */
    MySQLConnection c = new MySQLConnection();
    public ReturnBikeJFrame() {
        initComponents();
        DisplayCarOnRent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReturnBikePanel = new javax.swing.JPanel();
        LblReturnBikeHeading = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        BtnRentBike = new javax.swing.JButton();
        BtnManageBike = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblBikeOnRent = new javax.swing.JTable();
        LblRentalRequest = new javax.swing.JLabel();
        LblCustomerID = new javax.swing.JLabel();
        LblBrand = new javax.swing.JLabel();
        LblStatus = new javax.swing.JLabel();
        TxtCustomerID = new javax.swing.JTextField();
        TxtRentID = new javax.swing.JTextField();
        BtnConfirm = new javax.swing.JButton();
        LblModel = new javax.swing.JLabel();
        LblPrice = new javax.swing.JLabel();
        TxtDelay = new javax.swing.JTextField();
        TxtRegNo = new javax.swing.JTextField();
        TxtFine = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReturnBikePanel.setBackground(new java.awt.Color(12, 176, 176));

        LblReturnBikeHeading.setBackground(new java.awt.Color(161, 215, 215));
        LblReturnBikeHeading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblReturnBikeHeading.setForeground(new java.awt.Color(255, 255, 255));
        LblReturnBikeHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblReturnBikeHeading.setText("Return Bikes");
        LblReturnBikeHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonsPanel.setBackground(new java.awt.Color(0, 102, 102));

        BtnRentBike.setBackground(new java.awt.Color(162, 215, 215));
        BtnRentBike.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnRentBike.setText("Rent Bike");
        BtnRentBike.setBorder(null);
        BtnRentBike.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRentBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRentBikeActionPerformed(evt);
            }
        });

        BtnManageBike.setBackground(new java.awt.Color(162, 215, 215));
        BtnManageBike.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnManageBike.setText("Manage Bike");
        BtnManageBike.setBorder(null);
        BtnManageBike.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnManageBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageBikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnManageBike, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRentBike, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnManageBike, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BtnRentBike, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );

        TblBikeOnRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Duration", "Model", "Brand"
            }
        ));
        TblBikeOnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblBikeOnRentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblBikeOnRent);

        LblRentalRequest.setText("Rental Request");

        LblCustomerID.setText("Customer ID");

        LblBrand.setText("Rent ID");

        LblStatus.setText("Delay :");

        TxtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCustomerIDActionPerformed(evt);
            }
        });

        TxtRentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRentIDActionPerformed(evt);
            }
        });

        BtnConfirm.setText("Confirm");
        BtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmActionPerformed(evt);
            }
        });

        LblModel.setText("Reg No :");

        LblPrice.setText("Fine :");

        javax.swing.GroupLayout ReturnBikePanelLayout = new javax.swing.GroupLayout(ReturnBikePanel);
        ReturnBikePanel.setLayout(ReturnBikePanelLayout);
        ReturnBikePanelLayout.setHorizontalGroup(
            ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnBikePanelLayout.createSequentialGroup()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(LblRentalRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LblCustomerID)
                                        .addComponent(LblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79)
                        .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConfirm)
                            .addComponent(TxtRentID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFine, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblReturnBikeHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        ReturnBikePanelLayout.setVerticalGroup(
            ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblReturnBikeHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LblRentalRequest)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCustomerID)
                    .addComponent(TxtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBrand)
                    .addComponent(TxtRentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblModel)
                    .addComponent(TxtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addComponent(LblStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ReturnBikePanelLayout.createSequentialGroup()
                        .addComponent(TxtDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ReturnBikePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(BtnConfirm)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReturnBikePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReturnBikePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRentBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRentBikeActionPerformed
        // TODO add your handling code here:
        RentBikeJFrame rc = new RentBikeJFrame();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRentBikeActionPerformed

    private void BtnManageBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageBikeActionPerformed
        // TODO add your handling code here:
        ManageBikeJFrame mc = new ManageBikeJFrame();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnManageBikeActionPerformed

    private void TxtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCustomerIDActionPerformed

    private void BtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE customers SET customerid = '"+TxtCustomerID.getText()+"', delay = '"+TxtDelay.getText()+"', fine= '"+TxtFine.getText()+"',carapprove = 'Returned' WHERE customerid = '"+TxtCustomerID.getText()+"' ";
            c.updateDatabase(sql);
            JOptionPane.showMessageDialog(this,"Return Confirmed");
            String sql1 ="UPDATE car SET status = 'Available', rentid = NULL  WHERE Regno = '"+TxtRegNo.getText()+"'";
            c.updateDatabase(sql1);
 
            DisplayCarOnRent();

        }
        catch(Exception e)
        {
        e.printStackTrace();
    }
    }//GEN-LAST:event_BtnConfirmActionPerformed

    private void TblBikeOnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblBikeOnRentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TblBikeOnRent.getModel();
        int MyIndex = TblBikeOnRent.getSelectedRow();
        TxtCustomerID.setText(model.getValueAt(MyIndex,2).toString());
        TxtRentID.setText(model.getValueAt(MyIndex,1).toString());
        TxtRegNo.setText(model.getValueAt(MyIndex,0).toString());
    }//GEN-LAST:event_TblBikeOnRentMouseClicked

    private void TxtRentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBikeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBikeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBikeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBikeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBikeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirm;
    private javax.swing.JButton BtnManageBike;
    private javax.swing.JButton BtnRentBike;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel LblBrand;
    private javax.swing.JLabel LblCustomerID;
    private javax.swing.JLabel LblModel;
    private javax.swing.JLabel LblPrice;
    private javax.swing.JLabel LblRentalRequest;
    private javax.swing.JLabel LblReturnBikeHeading;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JPanel ReturnBikePanel;
    private javax.swing.JTable TblBikeOnRent;
    private javax.swing.JTextField TxtCustomerID;
    private javax.swing.JTextField TxtDelay;
    private javax.swing.JTextField TxtFine;
    private javax.swing.JTextField TxtRegNo;
    private javax.swing.JTextField TxtRentID;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void DisplayCarOnRent() {
        String reg,brand,carmodel,status,price;
        try{
            String sql = "select * from car where status = 'Booked' and rentid IS NOT NULL";
            ResultSet rs = c.selectDatabase(sql);
            DefaultTableModel model =(DefaultTableModel) TblBikeOnRent.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
            }
            while (rs.next()) {
                reg = rs.getString(2);
                brand = rs.getString(9);
                carmodel = rs.getString(6);
                status = rs.getString(1);
                String[] row = {status,reg,brand,carmodel};
                model.addRow(row);                  
            }
        } 
        catch (SQLException e)
        {
            e.printStackTrace();    
        }
    
    }
}
